// <auto-generated />
using System;
using EF_MOM_3_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_MOM_3_2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220221234050_AlbumChange")]
    partial class AlbumChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("EF_MOM_3_2.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("EF_MOM_3_2.Models.CD", b =>
                {
                    b.Property<int>("CDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateLent")
                        .HasColumnType("TEXT");

                    b.HasKey("CDId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CD");
                });

            modelBuilder.Entity("EF_MOM_3_2.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("EF_MOM_3_2.Models.CD", b =>
                {
                    b.HasOne("EF_MOM_3_2.Models.Artist", "Artist")
                        .WithMany("CD")
                        .HasForeignKey("ArtistId");

                    b.HasOne("EF_MOM_3_2.Models.Customer", "Customer")
                        .WithMany("CD")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Artist");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EF_MOM_3_2.Models.Artist", b =>
                {
                    b.Navigation("CD");
                });

            modelBuilder.Entity("EF_MOM_3_2.Models.Customer", b =>
                {
                    b.Navigation("CD");
                });
#pragma warning restore 612, 618
        }
    }
}
